import Foundation

/// Writes one `Localizable.strings` file per locale into `<outputDirectory>/<locale>.lproj/`.
public struct StringsFileGenerator {

    public enum GeneratorError: Error, CustomStringConvertible {
        case cannotCreateDirectory(URL, Error)
        case cannotWriteFile(URL, Error)

        public var description: String {
            switch self {
            case .cannotCreateDirectory(let url, let err):
                return "Cannot create directory '\(url.path)': \(err.localizedDescription)"
            case .cannotWriteFile(let url, let err):
                return "Cannot write file '\(url.path)': \(err.localizedDescription)"
            }
        }
    }

    public struct GenerationResult {
        public let locale: String
        public let fileURL: URL
        public let keyCount: Int
    }

    /// Generate `.strings` files for every locale found in `data`.
    ///
    /// - Parameters:
    ///   - data: Parsed CSV data containing locale columns and translation rows.
    ///   - outputDirectory: Root directory; `<locale>.lproj/` subdirectories are created here.
    /// - Returns: One result per locale describing what was written.
    @discardableResult
    public static func generate(
        from data: CSVParser.ParsedData,
        outputDirectory: URL
    ) throws -> [GenerationResult] {
        let fm = FileManager.default

        do {
            try fm.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        } catch {
            throw GeneratorError.cannotCreateDirectory(outputDirectory, error)
        }

        var results: [GenerationResult] = []

        for locale in data.locales {
            let lprojURL = outputDirectory.appendingPathComponent("\(locale).lproj")

            do {
                try fm.createDirectory(at: lprojURL, withIntermediateDirectories: true)
            } catch {
                throw GeneratorError.cannotCreateDirectory(lprojURL, error)
            }

            let fileURL  = lprojURL.appendingPathComponent("Localizable.strings")
            let content  = buildContent(for: locale, rows: data.rows)
            let keyCount = data.rows.filter { $0.translations[locale] != nil }.count

            do {
                try content.write(to: fileURL, atomically: true, encoding: .utf8)
            } catch {
                throw GeneratorError.cannotWriteFile(fileURL, error)
            }

            results.append(GenerationResult(locale: locale, fileURL: fileURL, keyCount: keyCount))
        }

        return results
    }

    // MARK: - Private helpers

    private static func buildContent(for locale: String, rows: [CSVParser.ParsedData.Row]) -> String {
        var lines: [String] = [
            "// Generated by LocalizationTool — do not edit manually.",
            "// Re-generated automatically from the CSV localization file on every build.",
            ""
        ]

        for row in rows {
            guard let value = row.translations[locale] else { continue }

            // Use `id` as the human-readable comment when available
            if !row.id.isEmpty {
                lines.append("/* \(row.id) */")
            }
            lines.append("\"\(escape(row.key))\" = \"\(escape(value))\";\n")
        }

        return lines.joined(separator: "\n")
    }

    /// Escapes characters that have special meaning inside a `.strings` quoted value.
    private static func escape(_ text: String) -> String {
        text
            .replacingOccurrences(of: "\\", with: "\\\\")   // must be first
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }
}
