# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: LocalizableTool

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Check Coverage Threshold
      uses: mattpolzin/swift-codecov-action@v0.7.5
      with:
        # Set this to your package name to exclude external dependencies
        PROJECT_NAME: "LocalizationTool" 
        # Minimum coverage percentage (0.0 to 100.0)
        MINIMUM_COVERAGE: 80.0
